Full website
abrormukimov/react-math pull request #5
Opened 2022-01-19 18:48 UTC by abrormukimov

# In this milestone:

- I added multiple pages

2022-01-19 19:28 UTC, julie-ify requested changes
## Hi @abrormukimov,

Good job so far!

## Highlight!
- Good feature branch name ✔️ 
- No linter errors ✔️  
- Good code organization and working app ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 19:28 UTC, julie-ify commented on src/App.js
> +      />
- [ ] Let's make the `<Home />` to have the root path route `/` and `<Calculator />` to have `/Calculator` path as the home page is always the root path. Also, it's a requirement. See suggestion:

```suggestion
    <Routes>
      <Route
        path="/"
        element={(
           <Home />
        )}
        exact
      />
      <Route
        path="/Calculator"
        element={
          <Calculator />
        }
        exact
      />
```

2022-01-19 19:28 UTC, julie-ify commented on src/components/Calculator.js
>      </div>
- [ ] Let's add the left text to our Calculator page so as to match the wireframe.

 Your Implementation | Wireframe
:---:|:---:
![](https://i.imgur.com/uNQq6S8.png) | ![](https://i.imgur.com/o7zgtZ1.png)

2022-01-21 04:43 UTC, Emmyn5600 approved these changes
Hi @abrormukimov 

Wooow👏, Your project is complete!  There is nothing else to say other than... it's time to merge it. 👏

Congratulations! 🎉 

##  Optional suggestion

- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-01-21 04:58 UTC, merged